cmd_/home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/board_imx6ull_qemu_led.o := arm-linux-gnueabihf-gcc -Wp,-MD,/home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/.board_imx6ull_qemu_led.o.d  -nostdinc -isystem /home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/ToolChain/gcc-linaro-6.2.1-2016.11-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/6.2.1/include -I./arch/arm/include -I./arch/arm/include/generated/uapi -I./arch/arm/include/generated  -I./include -I./arch/arm/include/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -fno-dwarf2-cfi-asm -fno-ipa-sra -mabi=aapcs-linux -mno-thumb-interwork -mfpu=vfp -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -fno-delete-null-pointer-checks -Wno-frame-address -O2 --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -Wno-unused-const-variable -fomit-frame-pointer -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types  -DMODULE  -DKBUILD_BASENAME='"board_imx6ull_qemu_led"'  -DKBUILD_MODNAME='"kxb_led"' -c -o /home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/.tmp_board_imx6ull_qemu_led.o /home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/board_imx6ull_qemu_led.c

source_/home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/board_imx6ull_qemu_led.o := /home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/board_imx6ull_qemu_led.c

deps_/home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/board_imx6ull_qemu_led.o := \
  /home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/led_reource.h \

/home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/board_imx6ull_qemu_led.o: $(deps_/home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/board_imx6ull_qemu_led.o)

$(deps_/home/kk-1988/work/qemu/src/100ask_imx6ull-qemu/drv/new_broad_test/02_led_drv/03_led_drv_template_seperate/board_imx6ull_qemu_led.o):
